#
#
#server:
#  port: 8082
#
#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: user_db
#  application:
#    name: USER-service
#
#eureka:
#  instance:
#    ip-address: true
#  client:
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8090/eureka
resilience4j.circuitbreaker:
 instances:
     cart_product23:
         registerHealthIndicator: true
         slidingWindowSize: 10
         permittedNumberOfCallsInHalfOpenState: 3
         slidingWindowType: TIME_BASED
      
resilience4j.timelimiter:
 instances:
     cart_product23:
         timeoutDuration: 2s
         cancelRunningFuture: true 
