insert into game values(1,'Action','WildServer')
insert into game values(2,'Action','COD')
insert into game values(3,'Puzzle','Puzz')
insert into game values(4,'Sports','CricketMe')
insert into game values(5,'Mind','Chess')
insert into game values(6,'Enemy','Lose')
