server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
spring:
  application:
    name: book-client
  data:
    mongodb:
      uri: http://localhost:27017
      database: book_db